# Generated by Django 2.2 on 2021-06-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('random_collection_app', '0002_auto_20210616_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_wall', to='random_collection_app.User'),
            preserve_default=False,
        ),
    ]
