# Generated by Django 2.2 on 2021-06-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_collection_app', '0004_auto_20210616_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='owner',
            new_name='owners',
        ),
    ]
